// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: 4_task.proto

package rpc_impl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file__4_task_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file__4_task_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file__4_task_proto_rawDescGZIP(), []int{0}
}

type Task_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId      string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskName    string   `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PreTaskIds  []string `protobuf:"bytes,4,rep,name=pre_task_ids,json=preTaskIds,proto3" json:"pre_task_ids,omitempty"`
	Status      uint32   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	UpdateTime  int64    `protobuf:"varint,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	CreatedTime int64    `protobuf:"varint,7,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
}

func (x *Task_Data) Reset() {
	*x = Task_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file__4_task_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Data) ProtoMessage() {}

func (x *Task_Data) ProtoReflect() protoreflect.Message {
	mi := &file__4_task_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Data.ProtoReflect.Descriptor instead.
func (*Task_Data) Descriptor() ([]byte, []int) {
	return file__4_task_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Task_Data) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task_Data) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *Task_Data) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task_Data) GetPreTaskIds() []string {
	if x != nil {
		return x.PreTaskIds
	}
	return nil
}

func (x *Task_Data) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Task_Data) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Task_Data) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

type Task_ListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperatorId string `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
}

func (x *Task_ListReq) Reset() {
	*x = Task_ListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file__4_task_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_ListReq) ProtoMessage() {}

func (x *Task_ListReq) ProtoReflect() protoreflect.Message {
	mi := &file__4_task_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_ListReq.ProtoReflect.Descriptor instead.
func (*Task_ListReq) Descriptor() ([]byte, []int) {
	return file__4_task_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Task_ListReq) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

type Task_ListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Tasks []*Task_Data `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Err   *Error       `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Task_ListRes) Reset() {
	*x = Task_ListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file__4_task_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_ListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_ListRes) ProtoMessage() {}

func (x *Task_ListRes) ProtoReflect() protoreflect.Message {
	mi := &file__4_task_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_ListRes.ProtoReflect.Descriptor instead.
func (*Task_ListRes) Descriptor() ([]byte, []int) {
	return file__4_task_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Task_ListRes) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Task_ListRes) GetTasks() []*Task_Data {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Task_ListRes) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type Task_CreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperatorId  string   `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	TaskName    string   `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PreTaskIds  []string `protobuf:"bytes,4,rep,name=pre_task_ids,json=preTaskIds,proto3" json:"pre_task_ids,omitempty"`
}

func (x *Task_CreateReq) Reset() {
	*x = Task_CreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file__4_task_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_CreateReq) ProtoMessage() {}

func (x *Task_CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file__4_task_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_CreateReq.ProtoReflect.Descriptor instead.
func (*Task_CreateReq) Descriptor() ([]byte, []int) {
	return file__4_task_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Task_CreateReq) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *Task_CreateReq) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *Task_CreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task_CreateReq) GetPreTaskIds() []string {
	if x != nil {
		return x.PreTaskIds
	}
	return nil
}

type Task_CreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *Error `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Task_CreateRes) Reset() {
	*x = Task_CreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file__4_task_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_CreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_CreateRes) ProtoMessage() {}

func (x *Task_CreateRes) ProtoReflect() protoreflect.Message {
	mi := &file__4_task_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_CreateRes.ProtoReflect.Descriptor instead.
func (*Task_CreateRes) Descriptor() ([]byte, []int) {
	return file__4_task_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Task_CreateRes) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type Task_ModifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperatorId  string   `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	TaskId      string   `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Password    string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	TaskName    string   `protobuf:"bytes,4,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Description string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	PreTaskIds  []string `protobuf:"bytes,6,rep,name=pre_task_ids,json=preTaskIds,proto3" json:"pre_task_ids,omitempty"`
	Status      uint32   `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Task_ModifyReq) Reset() {
	*x = Task_ModifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file__4_task_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_ModifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_ModifyReq) ProtoMessage() {}

func (x *Task_ModifyReq) ProtoReflect() protoreflect.Message {
	mi := &file__4_task_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_ModifyReq.ProtoReflect.Descriptor instead.
func (*Task_ModifyReq) Descriptor() ([]byte, []int) {
	return file__4_task_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Task_ModifyReq) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *Task_ModifyReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task_ModifyReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Task_ModifyReq) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *Task_ModifyReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task_ModifyReq) GetPreTaskIds() []string {
	if x != nil {
		return x.PreTaskIds
	}
	return nil
}

func (x *Task_ModifyReq) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Task_ModifyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *Error `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Task_ModifyRes) Reset() {
	*x = Task_ModifyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file__4_task_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_ModifyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_ModifyRes) ProtoMessage() {}

func (x *Task_ModifyRes) ProtoReflect() protoreflect.Message {
	mi := &file__4_task_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_ModifyRes.ProtoReflect.Descriptor instead.
func (*Task_ModifyRes) Descriptor() ([]byte, []int) {
	return file__4_task_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Task_ModifyRes) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

var File__4_task_proto protoreflect.FileDescriptor

var file__4_task_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x34, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x74, 0x61, 0x73, 0x6b, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xc3, 0x06, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0xdc, 0x01, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0c,
	0x70, 0x72, 0x65, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x2a, 0x0a, 0x07, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x1a, 0x67, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x1f,
	0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x1a,
	0x8d, 0x01, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a,
	0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a,
	0x0c, 0x70, 0x72, 0x65, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x73, 0x1a,
	0x2c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x1a, 0xda, 0x01,
	0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x20, 0x0a, 0x0c, 0x70, 0x72, 0x65, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x2c, 0x0a, 0x09, 0x4d, 0x6f,
	0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x32, 0xa3, 0x01, 0x0a, 0x05, 0x49, 0x54, 0x61,
	0x73, 0x6b, 0x12, 0x2e, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x74, 0x61, 0x73,
	0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12,
	0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x74,
	0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x12, 0x14, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x42, 0x0e,
	0x48, 0x03, 0x5a, 0x0a, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x69, 0x6d, 0x70, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file__4_task_proto_rawDescOnce sync.Once
	file__4_task_proto_rawDescData = file__4_task_proto_rawDesc
)

func file__4_task_proto_rawDescGZIP() []byte {
	file__4_task_proto_rawDescOnce.Do(func() {
		file__4_task_proto_rawDescData = protoimpl.X.CompressGZIP(file__4_task_proto_rawDescData)
	})
	return file__4_task_proto_rawDescData
}

var file__4_task_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file__4_task_proto_goTypes = []interface{}{
	(*Task)(nil),           // 0: task.Task
	(*Task_Data)(nil),      // 1: task.Task.Data
	(*Task_ListReq)(nil),   // 2: task.Task.ListReq
	(*Task_ListRes)(nil),   // 3: task.Task.ListRes
	(*Task_CreateReq)(nil), // 4: task.Task.CreateReq
	(*Task_CreateRes)(nil), // 5: task.Task.CreateRes
	(*Task_ModifyReq)(nil), // 6: task.Task.ModifyReq
	(*Task_ModifyRes)(nil), // 7: task.Task.ModifyRes
	(*Error)(nil),          // 8: common.Error
}
var file__4_task_proto_depIdxs = []int32{
	1, // 0: task.Task.ListRes.tasks:type_name -> task.Task.Data
	8, // 1: task.Task.ListRes.err:type_name -> common.Error
	8, // 2: task.Task.CreateRes.err:type_name -> common.Error
	8, // 3: task.Task.ModifyRes.err:type_name -> common.Error
	2, // 4: task.ITask.List:input_type -> task.Task.ListReq
	4, // 5: task.ITask.Create:input_type -> task.Task.CreateReq
	6, // 6: task.ITask.Modify:input_type -> task.Task.ModifyReq
	3, // 7: task.ITask.List:output_type -> task.Task.ListRes
	5, // 8: task.ITask.Create:output_type -> task.Task.CreateRes
	7, // 9: task.ITask.Modify:output_type -> task.Task.ModifyRes
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file__4_task_proto_init() }
func file__4_task_proto_init() {
	if File__4_task_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file__4_task_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__4_task_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__4_task_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_ListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__4_task_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_ListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__4_task_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_CreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__4_task_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_CreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__4_task_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_ModifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__4_task_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_ModifyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file__4_task_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file__4_task_proto_goTypes,
		DependencyIndexes: file__4_task_proto_depIdxs,
		MessageInfos:      file__4_task_proto_msgTypes,
	}.Build()
	File__4_task_proto = out.File
	file__4_task_proto_rawDesc = nil
	file__4_task_proto_goTypes = nil
	file__4_task_proto_depIdxs = nil
}
