// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: registration_center.proto

package rpc_impl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationCenterCore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegistrationCenterCore) Reset() {
	*x = RegistrationCenterCore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registration_center_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationCenterCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationCenterCore) ProtoMessage() {}

func (x *RegistrationCenterCore) ProtoReflect() protoreflect.Message {
	mi := &file_registration_center_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationCenterCore.ProtoReflect.Descriptor instead.
func (*RegistrationCenterCore) Descriptor() ([]byte, []int) {
	return file_registration_center_proto_rawDescGZIP(), []int{0}
}

type RegistrationCenterEmbedded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegistrationCenterEmbedded) Reset() {
	*x = RegistrationCenterEmbedded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registration_center_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationCenterEmbedded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationCenterEmbedded) ProtoMessage() {}

func (x *RegistrationCenterEmbedded) ProtoReflect() protoreflect.Message {
	mi := &file_registration_center_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationCenterEmbedded.ProtoReflect.Descriptor instead.
func (*RegistrationCenterEmbedded) Descriptor() ([]byte, []int) {
	return file_registration_center_proto_rawDescGZIP(), []int{1}
}

type RegistrationCenterCore_RegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId string `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Target    string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // ip+port, like '127.0.0.1:8080'
}

func (x *RegistrationCenterCore_RegisterReq) Reset() {
	*x = RegistrationCenterCore_RegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registration_center_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationCenterCore_RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationCenterCore_RegisterReq) ProtoMessage() {}

func (x *RegistrationCenterCore_RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_registration_center_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationCenterCore_RegisterReq.ProtoReflect.Descriptor instead.
func (*RegistrationCenterCore_RegisterReq) Descriptor() ([]byte, []int) {
	return file_registration_center_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RegistrationCenterCore_RegisterReq) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegistrationCenterCore_RegisterReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type RegistrationCenterCore_RegisterRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *Error `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *RegistrationCenterCore_RegisterRes) Reset() {
	*x = RegistrationCenterCore_RegisterRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registration_center_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationCenterCore_RegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationCenterCore_RegisterRes) ProtoMessage() {}

func (x *RegistrationCenterCore_RegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_registration_center_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationCenterCore_RegisterRes.ProtoReflect.Descriptor instead.
func (*RegistrationCenterCore_RegisterRes) Descriptor() ([]byte, []int) {
	return file_registration_center_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RegistrationCenterCore_RegisterRes) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type RegistrationCenterCore_ListServiceTargetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId string `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
}

func (x *RegistrationCenterCore_ListServiceTargetReq) Reset() {
	*x = RegistrationCenterCore_ListServiceTargetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registration_center_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationCenterCore_ListServiceTargetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationCenterCore_ListServiceTargetReq) ProtoMessage() {}

func (x *RegistrationCenterCore_ListServiceTargetReq) ProtoReflect() protoreflect.Message {
	mi := &file_registration_center_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationCenterCore_ListServiceTargetReq.ProtoReflect.Descriptor instead.
func (*RegistrationCenterCore_ListServiceTargetReq) Descriptor() ([]byte, []int) {
	return file_registration_center_proto_rawDescGZIP(), []int{0, 2}
}

func (x *RegistrationCenterCore_ListServiceTargetReq) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type RegistrationCenterCore_ListServiceTargetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Targets []string `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	Err     *Error   `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *RegistrationCenterCore_ListServiceTargetRes) Reset() {
	*x = RegistrationCenterCore_ListServiceTargetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registration_center_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationCenterCore_ListServiceTargetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationCenterCore_ListServiceTargetRes) ProtoMessage() {}

func (x *RegistrationCenterCore_ListServiceTargetRes) ProtoReflect() protoreflect.Message {
	mi := &file_registration_center_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationCenterCore_ListServiceTargetRes.ProtoReflect.Descriptor instead.
func (*RegistrationCenterCore_ListServiceTargetRes) Descriptor() ([]byte, []int) {
	return file_registration_center_proto_rawDescGZIP(), []int{0, 3}
}

func (x *RegistrationCenterCore_ListServiceTargetRes) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *RegistrationCenterCore_ListServiceTargetRes) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type RegistrationCenterEmbedded_CheckHealthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // useless data, like 'ping'
}

func (x *RegistrationCenterEmbedded_CheckHealthReq) Reset() {
	*x = RegistrationCenterEmbedded_CheckHealthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registration_center_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationCenterEmbedded_CheckHealthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationCenterEmbedded_CheckHealthReq) ProtoMessage() {}

func (x *RegistrationCenterEmbedded_CheckHealthReq) ProtoReflect() protoreflect.Message {
	mi := &file_registration_center_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationCenterEmbedded_CheckHealthReq.ProtoReflect.Descriptor instead.
func (*RegistrationCenterEmbedded_CheckHealthReq) Descriptor() ([]byte, []int) {
	return file_registration_center_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RegistrationCenterEmbedded_CheckHealthReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RegistrationCenterEmbedded_CheckHealthRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *Error `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *RegistrationCenterEmbedded_CheckHealthRes) Reset() {
	*x = RegistrationCenterEmbedded_CheckHealthRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registration_center_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationCenterEmbedded_CheckHealthRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationCenterEmbedded_CheckHealthRes) ProtoMessage() {}

func (x *RegistrationCenterEmbedded_CheckHealthRes) ProtoReflect() protoreflect.Message {
	mi := &file_registration_center_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationCenterEmbedded_CheckHealthRes.ProtoReflect.Descriptor instead.
func (*RegistrationCenterEmbedded_CheckHealthRes) Descriptor() ([]byte, []int) {
	return file_registration_center_proto_rawDescGZIP(), []int{1, 1}
}

func (x *RegistrationCenterEmbedded_CheckHealthRes) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

var File_registration_center_proto protoreflect.FileDescriptor

var file_registration_center_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x1a,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x02,
	0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x72, 0x65, 0x1a, 0x44, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x1a, 0x2e,
	0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x1a, 0x35,
	0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x1a, 0x51, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x75, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x45, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x1a, 0x24, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x31, 0x0a, 0x0e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x12, 0x1f,
	0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x32,
	0xad, 0x02, 0x0a, 0x17, 0x49, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x72, 0x65, 0x12, 0x7a, 0x0a, 0x08, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x36, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x43,
	0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x36, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x95, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x3f, 0x2e,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x3f,
	0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x72, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x32,
	0xab, 0x01, 0x0a, 0x1b, 0x49, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x12,
	0x8b, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12,
	0x3d, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x3d,
	0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x42, 0x0e, 0x48,
	0x03, 0x5a, 0x0a, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x69, 0x6d, 0x70, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_registration_center_proto_rawDescOnce sync.Once
	file_registration_center_proto_rawDescData = file_registration_center_proto_rawDesc
)

func file_registration_center_proto_rawDescGZIP() []byte {
	file_registration_center_proto_rawDescOnce.Do(func() {
		file_registration_center_proto_rawDescData = protoimpl.X.CompressGZIP(file_registration_center_proto_rawDescData)
	})
	return file_registration_center_proto_rawDescData
}

var file_registration_center_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_registration_center_proto_goTypes = []interface{}{
	(*RegistrationCenterCore)(nil),                      // 0: registrationCenter.RegistrationCenterCore
	(*RegistrationCenterEmbedded)(nil),                  // 1: registrationCenter.RegistrationCenterEmbedded
	(*RegistrationCenterCore_RegisterReq)(nil),          // 2: registrationCenter.RegistrationCenterCore.RegisterReq
	(*RegistrationCenterCore_RegisterRes)(nil),          // 3: registrationCenter.RegistrationCenterCore.RegisterRes
	(*RegistrationCenterCore_ListServiceTargetReq)(nil), // 4: registrationCenter.RegistrationCenterCore.ListServiceTargetReq
	(*RegistrationCenterCore_ListServiceTargetRes)(nil), // 5: registrationCenter.RegistrationCenterCore.ListServiceTargetRes
	(*RegistrationCenterEmbedded_CheckHealthReq)(nil),   // 6: registrationCenter.RegistrationCenterEmbedded.CheckHealthReq
	(*RegistrationCenterEmbedded_CheckHealthRes)(nil),   // 7: registrationCenter.RegistrationCenterEmbedded.CheckHealthRes
	(*Error)(nil), // 8: common.Error
}
var file_registration_center_proto_depIdxs = []int32{
	8, // 0: registrationCenter.RegistrationCenterCore.RegisterRes.err:type_name -> common.Error
	8, // 1: registrationCenter.RegistrationCenterCore.ListServiceTargetRes.err:type_name -> common.Error
	8, // 2: registrationCenter.RegistrationCenterEmbedded.CheckHealthRes.err:type_name -> common.Error
	2, // 3: registrationCenter.IRegistrationCenterCore.Register:input_type -> registrationCenter.RegistrationCenterCore.RegisterReq
	4, // 4: registrationCenter.IRegistrationCenterCore.ListServiceTarget:input_type -> registrationCenter.RegistrationCenterCore.ListServiceTargetReq
	6, // 5: registrationCenter.IRegistrationCenterEmbedded.CheckHealth:input_type -> registrationCenter.RegistrationCenterEmbedded.CheckHealthReq
	3, // 6: registrationCenter.IRegistrationCenterCore.Register:output_type -> registrationCenter.RegistrationCenterCore.RegisterRes
	5, // 7: registrationCenter.IRegistrationCenterCore.ListServiceTarget:output_type -> registrationCenter.RegistrationCenterCore.ListServiceTargetRes
	7, // 8: registrationCenter.IRegistrationCenterEmbedded.CheckHealth:output_type -> registrationCenter.RegistrationCenterEmbedded.CheckHealthRes
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_registration_center_proto_init() }
func file_registration_center_proto_init() {
	if File_registration_center_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_registration_center_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationCenterCore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registration_center_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationCenterEmbedded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registration_center_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationCenterCore_RegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registration_center_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationCenterCore_RegisterRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registration_center_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationCenterCore_ListServiceTargetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registration_center_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationCenterCore_ListServiceTargetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registration_center_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationCenterEmbedded_CheckHealthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registration_center_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationCenterEmbedded_CheckHealthRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_registration_center_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_registration_center_proto_goTypes,
		DependencyIndexes: file_registration_center_proto_depIdxs,
		MessageInfos:      file_registration_center_proto_msgTypes,
	}.Build()
	File_registration_center_proto = out.File
	file_registration_center_proto_rawDesc = nil
	file_registration_center_proto_goTypes = nil
	file_registration_center_proto_depIdxs = nil
}
