// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc_impl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IThinkingNoteClient is the client API for IThinkingNote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IThinkingNoteClient interface {
	ListByWriter(ctx context.Context, in *ThinkingNote_ListByWriterReq, opts ...grpc.CallOption) (*ThinkingNote_ListByWriterRes, error)
	ListPublic(ctx context.Context, in *ThinkingNote_ListPublicReq, opts ...grpc.CallOption) (*ThinkingNote_ListPublicRes, error)
	Create(ctx context.Context, in *ThinkingNote_CreateReq, opts ...grpc.CallOption) (*ThinkingNote_CreateRes, error)
	Modify(ctx context.Context, in *ThinkingNote_ModifyReq, opts ...grpc.CallOption) (*ThinkingNote_ModifyRes, error)
	Delete(ctx context.Context, in *ThinkingNote_DeleteReq, opts ...grpc.CallOption) (*ThinkingNote_DeleteRes, error)
}

type iThinkingNoteClient struct {
	cc grpc.ClientConnInterface
}

func NewIThinkingNoteClient(cc grpc.ClientConnInterface) IThinkingNoteClient {
	return &iThinkingNoteClient{cc}
}

func (c *iThinkingNoteClient) ListByWriter(ctx context.Context, in *ThinkingNote_ListByWriterReq, opts ...grpc.CallOption) (*ThinkingNote_ListByWriterRes, error) {
	out := new(ThinkingNote_ListByWriterRes)
	err := c.cc.Invoke(ctx, "/thinkingNote.IThinkingNote/ListByWriter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iThinkingNoteClient) ListPublic(ctx context.Context, in *ThinkingNote_ListPublicReq, opts ...grpc.CallOption) (*ThinkingNote_ListPublicRes, error) {
	out := new(ThinkingNote_ListPublicRes)
	err := c.cc.Invoke(ctx, "/thinkingNote.IThinkingNote/ListPublic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iThinkingNoteClient) Create(ctx context.Context, in *ThinkingNote_CreateReq, opts ...grpc.CallOption) (*ThinkingNote_CreateRes, error) {
	out := new(ThinkingNote_CreateRes)
	err := c.cc.Invoke(ctx, "/thinkingNote.IThinkingNote/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iThinkingNoteClient) Modify(ctx context.Context, in *ThinkingNote_ModifyReq, opts ...grpc.CallOption) (*ThinkingNote_ModifyRes, error) {
	out := new(ThinkingNote_ModifyRes)
	err := c.cc.Invoke(ctx, "/thinkingNote.IThinkingNote/Modify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iThinkingNoteClient) Delete(ctx context.Context, in *ThinkingNote_DeleteReq, opts ...grpc.CallOption) (*ThinkingNote_DeleteRes, error) {
	out := new(ThinkingNote_DeleteRes)
	err := c.cc.Invoke(ctx, "/thinkingNote.IThinkingNote/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IThinkingNoteServer is the server API for IThinkingNote service.
// All implementations must embed UnimplementedIThinkingNoteServer
// for forward compatibility
type IThinkingNoteServer interface {
	ListByWriter(context.Context, *ThinkingNote_ListByWriterReq) (*ThinkingNote_ListByWriterRes, error)
	ListPublic(context.Context, *ThinkingNote_ListPublicReq) (*ThinkingNote_ListPublicRes, error)
	Create(context.Context, *ThinkingNote_CreateReq) (*ThinkingNote_CreateRes, error)
	Modify(context.Context, *ThinkingNote_ModifyReq) (*ThinkingNote_ModifyRes, error)
	Delete(context.Context, *ThinkingNote_DeleteReq) (*ThinkingNote_DeleteRes, error)
	mustEmbedUnimplementedIThinkingNoteServer()
}

// UnimplementedIThinkingNoteServer must be embedded to have forward compatible implementations.
type UnimplementedIThinkingNoteServer struct {
}

func (UnimplementedIThinkingNoteServer) ListByWriter(context.Context, *ThinkingNote_ListByWriterReq) (*ThinkingNote_ListByWriterRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByWriter not implemented")
}
func (UnimplementedIThinkingNoteServer) ListPublic(context.Context, *ThinkingNote_ListPublicReq) (*ThinkingNote_ListPublicRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPublic not implemented")
}
func (UnimplementedIThinkingNoteServer) Create(context.Context, *ThinkingNote_CreateReq) (*ThinkingNote_CreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedIThinkingNoteServer) Modify(context.Context, *ThinkingNote_ModifyReq) (*ThinkingNote_ModifyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modify not implemented")
}
func (UnimplementedIThinkingNoteServer) Delete(context.Context, *ThinkingNote_DeleteReq) (*ThinkingNote_DeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedIThinkingNoteServer) mustEmbedUnimplementedIThinkingNoteServer() {}

// UnsafeIThinkingNoteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IThinkingNoteServer will
// result in compilation errors.
type UnsafeIThinkingNoteServer interface {
	mustEmbedUnimplementedIThinkingNoteServer()
}

func RegisterIThinkingNoteServer(s grpc.ServiceRegistrar, srv IThinkingNoteServer) {
	s.RegisterService(&IThinkingNote_ServiceDesc, srv)
}

func _IThinkingNote_ListByWriter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThinkingNote_ListByWriterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IThinkingNoteServer).ListByWriter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thinkingNote.IThinkingNote/ListByWriter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IThinkingNoteServer).ListByWriter(ctx, req.(*ThinkingNote_ListByWriterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IThinkingNote_ListPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThinkingNote_ListPublicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IThinkingNoteServer).ListPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thinkingNote.IThinkingNote/ListPublic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IThinkingNoteServer).ListPublic(ctx, req.(*ThinkingNote_ListPublicReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IThinkingNote_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThinkingNote_CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IThinkingNoteServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thinkingNote.IThinkingNote/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IThinkingNoteServer).Create(ctx, req.(*ThinkingNote_CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IThinkingNote_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThinkingNote_ModifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IThinkingNoteServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thinkingNote.IThinkingNote/Modify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IThinkingNoteServer).Modify(ctx, req.(*ThinkingNote_ModifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IThinkingNote_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThinkingNote_DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IThinkingNoteServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thinkingNote.IThinkingNote/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IThinkingNoteServer).Delete(ctx, req.(*ThinkingNote_DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IThinkingNote_ServiceDesc is the grpc.ServiceDesc for IThinkingNote service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IThinkingNote_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thinkingNote.IThinkingNote",
	HandlerType: (*IThinkingNoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListByWriter",
			Handler:    _IThinkingNote_ListByWriter_Handler,
		},
		{
			MethodName: "ListPublic",
			Handler:    _IThinkingNote_ListPublic_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _IThinkingNote_Create_Handler,
		},
		{
			MethodName: "Modify",
			Handler:    _IThinkingNote_Modify_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _IThinkingNote_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thinking_note.proto",
}
