// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: 2_cloud_file.proto

package rpc_impl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloudFile_ListRule int32

const (
	CloudFile_UNSPECIFIED CloudFile_ListRule = 0
	CloudFile_UPLOADER    CloudFile_ListRule = 1
	CloudFile_PUBLIC      CloudFile_ListRule = 2
)

// Enum value maps for CloudFile_ListRule.
var (
	CloudFile_ListRule_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UPLOADER",
		2: "PUBLIC",
	}
	CloudFile_ListRule_value = map[string]int32{
		"UNSPECIFIED": 0,
		"UPLOADER":    1,
		"PUBLIC":      2,
	}
)

func (x CloudFile_ListRule) Enum() *CloudFile_ListRule {
	p := new(CloudFile_ListRule)
	*p = x
	return p
}

func (x CloudFile_ListRule) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloudFile_ListRule) Descriptor() protoreflect.EnumDescriptor {
	return file__2_cloud_file_proto_enumTypes[0].Descriptor()
}

func (CloudFile_ListRule) Type() protoreflect.EnumType {
	return &file__2_cloud_file_proto_enumTypes[0]
}

func (x CloudFile_ListRule) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloudFile_ListRule.Descriptor instead.
func (CloudFile_ListRule) EnumDescriptor() ([]byte, []int) {
	return file__2_cloud_file_proto_rawDescGZIP(), []int{0, 0}
}

type CloudFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloudFile) Reset() {
	*x = CloudFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file__2_cloud_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudFile) ProtoMessage() {}

func (x *CloudFile) ProtoReflect() protoreflect.Message {
	mi := &file__2_cloud_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudFile.ProtoReflect.Descriptor instead.
func (*CloudFile) Descriptor() ([]byte, []int) {
	return file__2_cloud_file_proto_rawDescGZIP(), []int{0}
}

type CloudFile_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId           string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileName         string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	LastModifiedTime int64  `protobuf:"varint,3,opt,name=last_modified_time,json=lastModifiedTime,proto3" json:"last_modified_time,omitempty"`
	FileUrl          string `protobuf:"bytes,4,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	IsPublic         bool   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	UpdateTime       int64  `protobuf:"varint,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	CreatedTime      int64  `protobuf:"varint,7,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
}

func (x *CloudFile_Data) Reset() {
	*x = CloudFile_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file__2_cloud_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudFile_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudFile_Data) ProtoMessage() {}

func (x *CloudFile_Data) ProtoReflect() protoreflect.Message {
	mi := &file__2_cloud_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudFile_Data.ProtoReflect.Descriptor instead.
func (*CloudFile_Data) Descriptor() ([]byte, []int) {
	return file__2_cloud_file_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CloudFile_Data) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CloudFile_Data) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CloudFile_Data) GetLastModifiedTime() int64 {
	if x != nil {
		return x.LastModifiedTime
	}
	return 0
}

func (x *CloudFile_Data) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *CloudFile_Data) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *CloudFile_Data) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *CloudFile_Data) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

type CloudFile_ListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rule       CloudFile_ListRule `protobuf:"varint,1,opt,name=rule,proto3,enum=cloudFile.CloudFile_ListRule" json:"rule,omitempty"`
	OperatorId string             `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Page       *Pagination        `protobuf:"bytes,15,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *CloudFile_ListReq) Reset() {
	*x = CloudFile_ListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file__2_cloud_file_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudFile_ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudFile_ListReq) ProtoMessage() {}

func (x *CloudFile_ListReq) ProtoReflect() protoreflect.Message {
	mi := &file__2_cloud_file_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudFile_ListReq.ProtoReflect.Descriptor instead.
func (*CloudFile_ListReq) Descriptor() ([]byte, []int) {
	return file__2_cloud_file_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CloudFile_ListReq) GetRule() CloudFile_ListRule {
	if x != nil {
		return x.Rule
	}
	return CloudFile_UNSPECIFIED
}

func (x *CloudFile_ListReq) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *CloudFile_ListReq) GetPage() *Pagination {
	if x != nil {
		return x.Page
	}
	return nil
}

type CloudFile_ListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32            `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Files []*CloudFile_Data `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Err   *Error            `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *CloudFile_ListRes) Reset() {
	*x = CloudFile_ListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file__2_cloud_file_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudFile_ListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudFile_ListRes) ProtoMessage() {}

func (x *CloudFile_ListRes) ProtoReflect() protoreflect.Message {
	mi := &file__2_cloud_file_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudFile_ListRes.ProtoReflect.Descriptor instead.
func (*CloudFile_ListRes) Descriptor() ([]byte, []int) {
	return file__2_cloud_file_proto_rawDescGZIP(), []int{0, 2}
}

func (x *CloudFile_ListRes) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CloudFile_ListRes) GetFiles() []*CloudFile_Data {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *CloudFile_ListRes) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type CloudFile_UploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperatorId       string `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	File             []byte `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"` // file content
	FileName         string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ExtensionName    string `protobuf:"bytes,4,opt,name=extension_name,json=extensionName,proto3" json:"extension_name,omitempty"`
	FileSize         int64  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	LastModifiedTime int64  `protobuf:"varint,6,opt,name=last_modified_time,json=lastModifiedTime,proto3" json:"last_modified_time,omitempty"`
	IsPublic         bool   `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
}

func (x *CloudFile_UploadReq) Reset() {
	*x = CloudFile_UploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file__2_cloud_file_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudFile_UploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudFile_UploadReq) ProtoMessage() {}

func (x *CloudFile_UploadReq) ProtoReflect() protoreflect.Message {
	mi := &file__2_cloud_file_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudFile_UploadReq.ProtoReflect.Descriptor instead.
func (*CloudFile_UploadReq) Descriptor() ([]byte, []int) {
	return file__2_cloud_file_proto_rawDescGZIP(), []int{0, 3}
}

func (x *CloudFile_UploadReq) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *CloudFile_UploadReq) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *CloudFile_UploadReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CloudFile_UploadReq) GetExtensionName() string {
	if x != nil {
		return x.ExtensionName
	}
	return ""
}

func (x *CloudFile_UploadReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *CloudFile_UploadReq) GetLastModifiedTime() int64 {
	if x != nil {
		return x.LastModifiedTime
	}
	return 0
}

func (x *CloudFile_UploadReq) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type CloudFile_UploadRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *Error `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *CloudFile_UploadRes) Reset() {
	*x = CloudFile_UploadRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file__2_cloud_file_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudFile_UploadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudFile_UploadRes) ProtoMessage() {}

func (x *CloudFile_UploadRes) ProtoReflect() protoreflect.Message {
	mi := &file__2_cloud_file_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudFile_UploadRes.ProtoReflect.Descriptor instead.
func (*CloudFile_UploadRes) Descriptor() ([]byte, []int) {
	return file__2_cloud_file_proto_rawDescGZIP(), []int{0, 4}
}

func (x *CloudFile_UploadRes) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type CloudFile_ModifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required
	OperatorId string `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	FileId     string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Password   string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// option
	FileName      string `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ExtensionName string `protobuf:"bytes,5,opt,name=extension_name,json=extensionName,proto3" json:"extension_name,omitempty"`
	IsPublic      bool   `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	File          []byte `protobuf:"bytes,7,opt,name=file,proto3" json:"file,omitempty"`
	// required if 'file' is not null
	FileSize         int64 `protobuf:"varint,8,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	LastModifiedTime int64 `protobuf:"varint,9,opt,name=last_modified_time,json=lastModifiedTime,proto3" json:"last_modified_time,omitempty"`
}

func (x *CloudFile_ModifyReq) Reset() {
	*x = CloudFile_ModifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file__2_cloud_file_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudFile_ModifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudFile_ModifyReq) ProtoMessage() {}

func (x *CloudFile_ModifyReq) ProtoReflect() protoreflect.Message {
	mi := &file__2_cloud_file_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudFile_ModifyReq.ProtoReflect.Descriptor instead.
func (*CloudFile_ModifyReq) Descriptor() ([]byte, []int) {
	return file__2_cloud_file_proto_rawDescGZIP(), []int{0, 5}
}

func (x *CloudFile_ModifyReq) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *CloudFile_ModifyReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CloudFile_ModifyReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CloudFile_ModifyReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CloudFile_ModifyReq) GetExtensionName() string {
	if x != nil {
		return x.ExtensionName
	}
	return ""
}

func (x *CloudFile_ModifyReq) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *CloudFile_ModifyReq) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *CloudFile_ModifyReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *CloudFile_ModifyReq) GetLastModifiedTime() int64 {
	if x != nil {
		return x.LastModifiedTime
	}
	return 0
}

type CloudFile_ModifyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *Error `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *CloudFile_ModifyRes) Reset() {
	*x = CloudFile_ModifyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file__2_cloud_file_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudFile_ModifyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudFile_ModifyRes) ProtoMessage() {}

func (x *CloudFile_ModifyRes) ProtoReflect() protoreflect.Message {
	mi := &file__2_cloud_file_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudFile_ModifyRes.ProtoReflect.Descriptor instead.
func (*CloudFile_ModifyRes) Descriptor() ([]byte, []int) {
	return file__2_cloud_file_proto_rawDescGZIP(), []int{0, 6}
}

func (x *CloudFile_ModifyRes) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

type CloudFile_DeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperatorId string `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Password   string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FileId     string `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *CloudFile_DeleteReq) Reset() {
	*x = CloudFile_DeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file__2_cloud_file_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudFile_DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudFile_DeleteReq) ProtoMessage() {}

func (x *CloudFile_DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file__2_cloud_file_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudFile_DeleteReq.ProtoReflect.Descriptor instead.
func (*CloudFile_DeleteReq) Descriptor() ([]byte, []int) {
	return file__2_cloud_file_proto_rawDescGZIP(), []int{0, 7}
}

func (x *CloudFile_DeleteReq) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *CloudFile_DeleteReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CloudFile_DeleteReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type CloudFile_DeleteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *Error `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *CloudFile_DeleteRes) Reset() {
	*x = CloudFile_DeleteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file__2_cloud_file_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudFile_DeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudFile_DeleteRes) ProtoMessage() {}

func (x *CloudFile_DeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file__2_cloud_file_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudFile_DeleteRes.ProtoReflect.Descriptor instead.
func (*CloudFile_DeleteRes) Descriptor() ([]byte, []int) {
	return file__2_cloud_file_proto_rawDescGZIP(), []int{0, 8}
}

func (x *CloudFile_DeleteRes) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

var File__2_cloud_file_proto protoreflect.FileDescriptor

var file__2_cloud_file_proto_rawDesc = []byte{
	0x0a, 0x12, 0x32, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x1a,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x0a,
	0x0a, 0x09, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0xe6, 0x01, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65,
	0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x1a, 0x85, 0x01, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x31, 0x0a, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x04, 0x72,
	0x75, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x1a, 0x71, 0x0a, 0x07,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2f, 0x0a,
	0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1f,
	0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x1a,
	0xec, 0x01, 0x0a, 0x09, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a,
	0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x25, 0x0a, 0x0e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x10, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x1a, 0x2c,
	0x0a, 0x09, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x03, 0x65,
	0x72, 0x72, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x1a, 0xa1, 0x02, 0x0a,
	0x09, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10,
	0x6c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x1a, 0x2c, 0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x1a, 0x61,
	0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49,
	0x64, 0x1a, 0x2c, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x1f,
	0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22,
	0x35, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x55,
	0x42, 0x4c, 0x49, 0x43, 0x10, 0x02, 0x32, 0xae, 0x02, 0x0a, 0x0a, 0x49, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x42, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x48, 0x0a, 0x06, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x1e, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x2e,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x2e,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x12, 0x48, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x12, 0x1e, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x12, 0x48, 0x0a,
	0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x42, 0x0e, 0x48, 0x03, 0x5a, 0x0a, 0x2e, 0x2f, 0x72,
	0x70, 0x63, 0x5f, 0x69, 0x6d, 0x70, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file__2_cloud_file_proto_rawDescOnce sync.Once
	file__2_cloud_file_proto_rawDescData = file__2_cloud_file_proto_rawDesc
)

func file__2_cloud_file_proto_rawDescGZIP() []byte {
	file__2_cloud_file_proto_rawDescOnce.Do(func() {
		file__2_cloud_file_proto_rawDescData = protoimpl.X.CompressGZIP(file__2_cloud_file_proto_rawDescData)
	})
	return file__2_cloud_file_proto_rawDescData
}

var file__2_cloud_file_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file__2_cloud_file_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file__2_cloud_file_proto_goTypes = []interface{}{
	(CloudFile_ListRule)(0),     // 0: cloudFile.CloudFile.ListRule
	(*CloudFile)(nil),           // 1: cloudFile.CloudFile
	(*CloudFile_Data)(nil),      // 2: cloudFile.CloudFile.Data
	(*CloudFile_ListReq)(nil),   // 3: cloudFile.CloudFile.ListReq
	(*CloudFile_ListRes)(nil),   // 4: cloudFile.CloudFile.ListRes
	(*CloudFile_UploadReq)(nil), // 5: cloudFile.CloudFile.UploadReq
	(*CloudFile_UploadRes)(nil), // 6: cloudFile.CloudFile.UploadRes
	(*CloudFile_ModifyReq)(nil), // 7: cloudFile.CloudFile.ModifyReq
	(*CloudFile_ModifyRes)(nil), // 8: cloudFile.CloudFile.ModifyRes
	(*CloudFile_DeleteReq)(nil), // 9: cloudFile.CloudFile.DeleteReq
	(*CloudFile_DeleteRes)(nil), // 10: cloudFile.CloudFile.DeleteRes
	(*Pagination)(nil),          // 11: common.Pagination
	(*Error)(nil),               // 12: common.Error
}
var file__2_cloud_file_proto_depIdxs = []int32{
	0,  // 0: cloudFile.CloudFile.ListReq.rule:type_name -> cloudFile.CloudFile.ListRule
	11, // 1: cloudFile.CloudFile.ListReq.page:type_name -> common.Pagination
	2,  // 2: cloudFile.CloudFile.ListRes.files:type_name -> cloudFile.CloudFile.Data
	12, // 3: cloudFile.CloudFile.ListRes.err:type_name -> common.Error
	12, // 4: cloudFile.CloudFile.UploadRes.err:type_name -> common.Error
	12, // 5: cloudFile.CloudFile.ModifyRes.err:type_name -> common.Error
	12, // 6: cloudFile.CloudFile.DeleteRes.err:type_name -> common.Error
	3,  // 7: cloudFile.ICloudFile.List:input_type -> cloudFile.CloudFile.ListReq
	5,  // 8: cloudFile.ICloudFile.Upload:input_type -> cloudFile.CloudFile.UploadReq
	7,  // 9: cloudFile.ICloudFile.Modify:input_type -> cloudFile.CloudFile.ModifyReq
	9,  // 10: cloudFile.ICloudFile.Delete:input_type -> cloudFile.CloudFile.DeleteReq
	4,  // 11: cloudFile.ICloudFile.List:output_type -> cloudFile.CloudFile.ListRes
	6,  // 12: cloudFile.ICloudFile.Upload:output_type -> cloudFile.CloudFile.UploadRes
	8,  // 13: cloudFile.ICloudFile.Modify:output_type -> cloudFile.CloudFile.ModifyRes
	10, // 14: cloudFile.ICloudFile.Delete:output_type -> cloudFile.CloudFile.DeleteRes
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file__2_cloud_file_proto_init() }
func file__2_cloud_file_proto_init() {
	if File__2_cloud_file_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file__2_cloud_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__2_cloud_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudFile_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__2_cloud_file_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudFile_ListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__2_cloud_file_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudFile_ListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__2_cloud_file_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudFile_UploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__2_cloud_file_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudFile_UploadRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__2_cloud_file_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudFile_ModifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__2_cloud_file_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudFile_ModifyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__2_cloud_file_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudFile_DeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__2_cloud_file_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudFile_DeleteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file__2_cloud_file_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file__2_cloud_file_proto_goTypes,
		DependencyIndexes: file__2_cloud_file_proto_depIdxs,
		EnumInfos:         file__2_cloud_file_proto_enumTypes,
		MessageInfos:      file__2_cloud_file_proto_msgTypes,
	}.Build()
	File__2_cloud_file_proto = out.File
	file__2_cloud_file_proto_rawDesc = nil
	file__2_cloud_file_proto_goTypes = nil
	file__2_cloud_file_proto_depIdxs = nil
}
