// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc_impl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// INoteClient is the client API for INote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type INoteClient interface {
	List(ctx context.Context, in *Note_ListReq, opts ...grpc.CallOption) (*Note_ListRes, error)
	Create(ctx context.Context, in *Note_CreateReq, opts ...grpc.CallOption) (*Note_CreateRes, error)
	Modify(ctx context.Context, in *Note_ModifyReq, opts ...grpc.CallOption) (*Note_ModifyRes, error)
	Delete(ctx context.Context, in *Note_DeleteReq, opts ...grpc.CallOption) (*Note_DeleteRes, error)
}

type iNoteClient struct {
	cc grpc.ClientConnInterface
}

func NewINoteClient(cc grpc.ClientConnInterface) INoteClient {
	return &iNoteClient{cc}
}

func (c *iNoteClient) List(ctx context.Context, in *Note_ListReq, opts ...grpc.CallOption) (*Note_ListRes, error) {
	out := new(Note_ListRes)
	err := c.cc.Invoke(ctx, "/note.INote/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iNoteClient) Create(ctx context.Context, in *Note_CreateReq, opts ...grpc.CallOption) (*Note_CreateRes, error) {
	out := new(Note_CreateRes)
	err := c.cc.Invoke(ctx, "/note.INote/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iNoteClient) Modify(ctx context.Context, in *Note_ModifyReq, opts ...grpc.CallOption) (*Note_ModifyRes, error) {
	out := new(Note_ModifyRes)
	err := c.cc.Invoke(ctx, "/note.INote/Modify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iNoteClient) Delete(ctx context.Context, in *Note_DeleteReq, opts ...grpc.CallOption) (*Note_DeleteRes, error) {
	out := new(Note_DeleteRes)
	err := c.cc.Invoke(ctx, "/note.INote/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// INoteServer is the server API for INote service.
// All implementations must embed UnimplementedINoteServer
// for forward compatibility
type INoteServer interface {
	List(context.Context, *Note_ListReq) (*Note_ListRes, error)
	Create(context.Context, *Note_CreateReq) (*Note_CreateRes, error)
	Modify(context.Context, *Note_ModifyReq) (*Note_ModifyRes, error)
	Delete(context.Context, *Note_DeleteReq) (*Note_DeleteRes, error)
	mustEmbedUnimplementedINoteServer()
}

// UnimplementedINoteServer must be embedded to have forward compatible implementations.
type UnimplementedINoteServer struct {
}

func (UnimplementedINoteServer) List(context.Context, *Note_ListReq) (*Note_ListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedINoteServer) Create(context.Context, *Note_CreateReq) (*Note_CreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedINoteServer) Modify(context.Context, *Note_ModifyReq) (*Note_ModifyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modify not implemented")
}
func (UnimplementedINoteServer) Delete(context.Context, *Note_DeleteReq) (*Note_DeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedINoteServer) mustEmbedUnimplementedINoteServer() {}

// UnsafeINoteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to INoteServer will
// result in compilation errors.
type UnsafeINoteServer interface {
	mustEmbedUnimplementedINoteServer()
}

func RegisterINoteServer(s grpc.ServiceRegistrar, srv INoteServer) {
	s.RegisterService(&INote_ServiceDesc, srv)
}

func _INote_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Note_ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INoteServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/note.INote/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INoteServer).List(ctx, req.(*Note_ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _INote_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Note_CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INoteServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/note.INote/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INoteServer).Create(ctx, req.(*Note_CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _INote_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Note_ModifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INoteServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/note.INote/Modify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INoteServer).Modify(ctx, req.(*Note_ModifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _INote_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Note_DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INoteServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/note.INote/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INoteServer).Delete(ctx, req.(*Note_DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// INote_ServiceDesc is the grpc.ServiceDesc for INote service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var INote_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "note.INote",
	HandlerType: (*INoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _INote_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _INote_Create_Handler,
		},
		{
			MethodName: "Modify",
			Handler:    _INote_Modify_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _INote_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "3_note.proto",
}
