// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc_impl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ICloudFileClient is the client API for ICloudFile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ICloudFileClient interface {
	ListByUploader(ctx context.Context, in *CloudFileListByUploaderReq, opts ...grpc.CallOption) (*CloudFileListByUploaderRes, error)
	ListPublic(ctx context.Context, in *CloudFileListPublicReq, opts ...grpc.CallOption) (*CloudFileListPublicRes, error)
	Upload(ctx context.Context, in *CloudFileUploadReq, opts ...grpc.CallOption) (*Err, error)
	Modify(ctx context.Context, in *CloudFileModifyReq, opts ...grpc.CallOption) (*Err, error)
	Delete(ctx context.Context, in *CloudFileDeleteReq, opts ...grpc.CallOption) (*Err, error)
}

type iCloudFileClient struct {
	cc grpc.ClientConnInterface
}

func NewICloudFileClient(cc grpc.ClientConnInterface) ICloudFileClient {
	return &iCloudFileClient{cc}
}

func (c *iCloudFileClient) ListByUploader(ctx context.Context, in *CloudFileListByUploaderReq, opts ...grpc.CallOption) (*CloudFileListByUploaderRes, error) {
	out := new(CloudFileListByUploaderRes)
	err := c.cc.Invoke(ctx, "/cloudFile.ICloudFile/listByUploader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iCloudFileClient) ListPublic(ctx context.Context, in *CloudFileListPublicReq, opts ...grpc.CallOption) (*CloudFileListPublicRes, error) {
	out := new(CloudFileListPublicRes)
	err := c.cc.Invoke(ctx, "/cloudFile.ICloudFile/listPublic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iCloudFileClient) Upload(ctx context.Context, in *CloudFileUploadReq, opts ...grpc.CallOption) (*Err, error) {
	out := new(Err)
	err := c.cc.Invoke(ctx, "/cloudFile.ICloudFile/upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iCloudFileClient) Modify(ctx context.Context, in *CloudFileModifyReq, opts ...grpc.CallOption) (*Err, error) {
	out := new(Err)
	err := c.cc.Invoke(ctx, "/cloudFile.ICloudFile/modify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iCloudFileClient) Delete(ctx context.Context, in *CloudFileDeleteReq, opts ...grpc.CallOption) (*Err, error) {
	out := new(Err)
	err := c.cc.Invoke(ctx, "/cloudFile.ICloudFile/delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ICloudFileServer is the server API for ICloudFile service.
// All implementations must embed UnimplementedICloudFileServer
// for forward compatibility
type ICloudFileServer interface {
	ListByUploader(context.Context, *CloudFileListByUploaderReq) (*CloudFileListByUploaderRes, error)
	ListPublic(context.Context, *CloudFileListPublicReq) (*CloudFileListPublicRes, error)
	Upload(context.Context, *CloudFileUploadReq) (*Err, error)
	Modify(context.Context, *CloudFileModifyReq) (*Err, error)
	Delete(context.Context, *CloudFileDeleteReq) (*Err, error)
	mustEmbedUnimplementedICloudFileServer()
}

// UnimplementedICloudFileServer must be embedded to have forward compatible implementations.
type UnimplementedICloudFileServer struct {
}

func (UnimplementedICloudFileServer) ListByUploader(context.Context, *CloudFileListByUploaderReq) (*CloudFileListByUploaderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByUploader not implemented")
}
func (UnimplementedICloudFileServer) ListPublic(context.Context, *CloudFileListPublicReq) (*CloudFileListPublicRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPublic not implemented")
}
func (UnimplementedICloudFileServer) Upload(context.Context, *CloudFileUploadReq) (*Err, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedICloudFileServer) Modify(context.Context, *CloudFileModifyReq) (*Err, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modify not implemented")
}
func (UnimplementedICloudFileServer) Delete(context.Context, *CloudFileDeleteReq) (*Err, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedICloudFileServer) mustEmbedUnimplementedICloudFileServer() {}

// UnsafeICloudFileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ICloudFileServer will
// result in compilation errors.
type UnsafeICloudFileServer interface {
	mustEmbedUnimplementedICloudFileServer()
}

func RegisterICloudFileServer(s grpc.ServiceRegistrar, srv ICloudFileServer) {
	s.RegisterService(&ICloudFile_ServiceDesc, srv)
}

func _ICloudFile_ListByUploader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudFileListByUploaderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICloudFileServer).ListByUploader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudFile.ICloudFile/listByUploader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICloudFileServer).ListByUploader(ctx, req.(*CloudFileListByUploaderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ICloudFile_ListPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudFileListPublicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICloudFileServer).ListPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudFile.ICloudFile/listPublic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICloudFileServer).ListPublic(ctx, req.(*CloudFileListPublicReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ICloudFile_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudFileUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICloudFileServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudFile.ICloudFile/upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICloudFileServer).Upload(ctx, req.(*CloudFileUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ICloudFile_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudFileModifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICloudFileServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudFile.ICloudFile/modify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICloudFileServer).Modify(ctx, req.(*CloudFileModifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ICloudFile_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudFileDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ICloudFileServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudFile.ICloudFile/delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ICloudFileServer).Delete(ctx, req.(*CloudFileDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ICloudFile_ServiceDesc is the grpc.ServiceDesc for ICloudFile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ICloudFile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudFile.ICloudFile",
	HandlerType: (*ICloudFileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "listByUploader",
			Handler:    _ICloudFile_ListByUploader_Handler,
		},
		{
			MethodName: "listPublic",
			Handler:    _ICloudFile_ListPublic_Handler,
		},
		{
			MethodName: "upload",
			Handler:    _ICloudFile_Upload_Handler,
		},
		{
			MethodName: "modify",
			Handler:    _ICloudFile_Modify_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _ICloudFile_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloud_file.proto",
}
